name: Add latest tag to new push
on:
  push:
     branches:
      - master

jobs: 
  run:
    name: Add/update tag to new push
    runs-on: ubuntu-latest

    steps: 
    - name: Checkout repository
      uses: actions/checkout@master

    - name: Run latest-tag
      uses: EndBug/latest-tag@latest
      with:
        tag-name: latest
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # Leave this line unchanged
